name: CI Pipeline

on: 
  pull_request:
    branches:
      - main
    paths:
      - 'application/*'
      
  push:
    branches:
      - main
    paths:
      - 'application/*'

jobs:
  build:
    environment: devel
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: application
    steps: 
      - name: Check out code
        uses: actions/checkout@v5

      - name: Setup Nodejs
        uses: actions/setup-node@v5
        with:
          node-version-file: application/.nvmrc

      - name: Install dependencies
        run: npm install

      - name: Run linter
        run: npm run lint

      - name: Run formatter
        run: npm run prettier

      - name: Run tests
        env: 
          CI: true
        run: npm run test

      - name: Build project
        run: npm run build

      - name: Create Artifact
        uses: actions/upload-artifact@v4
        with:
          path: application/build
          name: bundle
    
  deploy:
    needs:
      - build
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.event_name == 'pull_request' && 'stage' || 'prod' }}
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v5.0.0
        with:
          aws-region: ${{ vars.AWS_REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Get Bundle
        uses: actions/download-artifact@v5
        with:
          name: bundle
          path: ./build

      - name: Rollout Appication
        run: aws s3 sync ./build s3://${{ vars.APPLICATION_BUCKET }}-${{ github.job.environment }} --delete