name: IaC

on:
  workflow_dispatch: {}

  
env:
  AWS_REGION: ${{ vars.AWS_REGION }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  validate:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: infrastructure
    steps:
      - name: Checkout Code
        uses: actions/checkout@v5

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init -backend-config="key=devel.tfstate"

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color

      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color -input=false

  provisioning:
    needs: 
      - validate
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: infrastructure
    strategy:
      matrix:
        environment: ["devel", "stage", "prod"]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v5

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init -backend-config="key=${{ matrix.environment }}.tfstate"

      - name: Terraform Apply
        run: terraform apply -auto-approve
        env:
          TF_VAR_environment=${{ matrix.environment }}