name: IaC

on:
  workflow_dispatch: {}

jobs:
  validate:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: infrastructure
    steps:
      - name: Checkout Code
        uses: actions/checkout@v5

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init -backend-config="key=devel.tfstate"

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color

      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color -input=false

  provisioning:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: infrastructure
    strategy:
      matrix:
        environment: ["devel", "stage", "prod"]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v5
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v5.0.0
        with:
          aws-region: ${{ vars.AWS_REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init -backend-config="key=${{ matrix.environment }}.tfstate"

      - name: Terraform Apply
        run: terraform apply -auto-approve