name: Rollout Pipeline

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Target environment"
        required: true
        type: environment

jobs:
  build:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    defaults:
      run:
        working-directory: application
    steps:
      - name: Check out code
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version-file: application/.nvmrc

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Create Artifact
        uses: actions/upload-artifact@v4
        with:
          path: application/build
          name: bundle

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v5.0.0
        with:
          aws-region: ${{ vars.AWS_REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Download Bundle
        uses: actions/download-artifact@v5
        with:
          name: bundle
          path: ./build

      - name: Rollout Application
        run: |
          aws s3 sync ./build s3://${{ vars.APPLICATION_BUCKET }}-${{ github.event.inputs.environment }} --delete
